export default {
  SET_COOKIE: 'SET_COOKIE',

  SET_API_ENGINE: 'SET_API_ENGINE',

  SET_TODO: 'SET_TODO',
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',

  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',

  UPDATE_LOCALE: 'UPDATE_LOCALE',

  PUSH_ERRORS: 'PUSH_ERRORS',
  REMOVE_ERROR: 'REMOVE_ERROR',

  SET_PAGE: 'SET_PAGE',
  SET_ENTITIES: 'SET_ENTITIES',
  SET_PAGES: 'SET_PAGES',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  PREPEND_ENTITIES_INTO_PAGE: 'PREPEND_ENTITIES_INTO_PAGE',
  APPEND_ENTITIES_INTO_PAGE: 'PUSH_ENTITIES_INTO_PAGE',
  REMOVE_ENTITIES_FROM_PAGE: 'REMOVE_ENTITIES_FROM_PAGE',
};
